### ISSUE TITLE
Make GitHub pages render on training.tweede.golf instead of tweedegolf.github.io/rust-training

### ISSUE THREAD

**Issue by hugovandepol** [tweedegolf/rust-training#43] opened 2024-08-14 14:57 UTC

**Comment by squell** [comment] 2024-08-15 10:08
Duplicate of #29, which is fixed already in the repo (but not yet deployed to the old website since we're in the process of removing that).

See: https://tweedegolf.github.io/rust-training/

We should update the link in the README though.

**Comment by squell** [comment] 2024-08-15 10:09
And also, make https://training.tweede.golf  forward to https://tweedegolf.github.io/rust-training/

**Comment by squell** [comment] 2024-08-27 12:03
That's now done!

**Closed by squell** 2024-08-27 12:03 UTC
